Needed to chg rpi2.cfg RPI2.CFG in the file jpeg-2000-test/bare-metal/openjp/compile.sh pi@mypi3-1:~ $ git clone https://github.com/develone/openjpeg.git t_ultibo Cloning into 't_ultibo'... remote: Enumerating objects: 26319, done. remote: Total 26319 (delta 0), reused 0 (delta 0), pack-reused 26319 Receiving objects: 100% (26319/26319), 75.00 MiB | 3.68 MiB/s, done. Resolving deltas: 100% (19082/19082), done.
pi@mypi3-1:~ $ cd t_ultibo/

git log

commit 0b4c3ce75d11600ebc6675bd871f78ca3c95bc60
Merge: a35b4891 9f750884
Author: Even Rouault <even.rouault@mines-paris.org>
Date:   Fri Aug 11 15:13:35 2017 +0200

    Merge pull request #980 from szukw000/changes-for-ppc64-converttif

    Changes in converttif.c for PPC64

pi@mypi3-1:~/t_ultibo $ git checkout ultibo
Branch ultibo set up to track remote branch ultibo from origin.
Switched to a new branch 'ultibo'

pi@mypi3-1:~/t_ultibo $ cd build/

pi@mypi3-1:~/t_ultibo/build $ cmake ../
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for string.h
-- Looking for string.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for math.h
-- Looking for math.h - found
-- Looking for float.h
-- Looking for float.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for assert.h
-- Looking for assert.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Checking for 64-bit off_t
-- Checking for 64-bit off_t - present with _FILE_OFFSET_BITS=64
-- Checking for fseeko/ftello
-- Checking for fseeko/ftello - present
-- Large File support - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for memalign
-- Looking for memalign - found
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.8")
-- Your system seems to have a Z lib available, we will use it to generate PNG lib
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.28")
-- Your system seems to have a PNG lib available, we will use it
-- Could NOT find TIFF (missing:  TIFF_LIBRARY TIFF_INCLUDE_DIR)
-- TIFF lib not found, activate BUILD_THIRDPARTY if you want build it
-- Could NOT find LCMS2 (missing:  LCMS2_LIBRARY LCMS2_INCLUDE_DIR)
-- Could NOT find LCMS (missing:  LCMS_LIBRARY LCMS_INCLUDE_DIR)
-- LCMS2 or LCMS lib not found, activate BUILD_THIRDPARTY if you want build it
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/t_ultibo/build

pi@mypi3-1:~/t_ultibo/build $ cd ../src/lib/openjp2

pi@mypi3-1:~/t_ultibo/src/lib/openjp2 $ cp ../../../*.h .

pi@mypi3-1:~/t_ultibo/src/lib/openjp2 $ ./compile_ultibo.sh
The word count here should be 22
the word count in /home/pi/jpeg-2000-test/bare-metal/openjp
when ./compile.sh is executed should be 23
Word count libopenjp2_obj.txt in /home/pi/t_ultibo/src/lib/openjp2
 22  22 180 libopenjp2_obj.txt

pi@mypi3-1:~/t_ultibo/src/lib/openjp2 $ cd ~/jpeg-2000-test/bare-metal/openjp/

pi@mypi3-1:~/jpeg-2000-test/bare-metal/openjp $ export PATH=/home/pi/ultibo/core/fpc/bin:$PATH

Needed to chg rpi2.cfg RPI2.CFG

pi@mypi3-1:~/jpeg-2000-test/bare-metal/openjp $ ./compile.sh
Wed Feb 27 13:08:53 MST 2019
Word count arm-none-eabi-ar -t libopenjp2.a
copied from /home/pi/t_ultibo/src/lib/openjp2
     22      22     180
dwtlift.c: In function 'decompress':
dwtlift.c:658:3: warning: implicit declaration of function 'octave_write_byte' [-Wimplicit-function-declaration]
   octave_write_byte(r_decompress_fn,r_decompress,da_x1*da_y1);
   ^
Free Pascal Compiler version 3.1.1 [2019/01/23] for arm
Copyright (c) 1993-2015 by Florian Klaempfl and others
Target OS: Ultibo
Compiling DWT_LIFT_RPi2.lpr
Compiling uTFTP.pas
Assembling utftp
Compiling uliftbitmap.pas
Compiling uBufferToC.pas
uliftbitmap.pas(88,2) Note: Local variable "FILTER" not used
Assembling uliftbitmap
DWT_LIFT_RPi2.lpr(196,4) Warning: Comment level 2 found
DWT_LIFT_RPi2.lpr(53,2) Note: Local variable "X" not used
DWT_LIFT_RPi2.lpr(54,2) Note: Local variable "Y" not used
DWT_LIFT_RPi2.lpr(55,2) Note: Local variable "Width" not used
DWT_LIFT_RPi2.lpr(56,2) Note: Local variable "Height" not used
Assembling dwt_lift_rpi2
Linking DWT_LIFT_RPi2
1126 lines compiled, 24.7 sec, 2911628 bytes code, 89940 bytes data
1 warning(s) issued
5 note(s) issued
-rw-r--r-- 1 pi pi   21400 Feb 27 13:08 dwtlift.o
-rwxr-xr-x 1 pi pi 2984884 Feb 27 13:09 kernel7.img
-rw-r--r-- 1 pi pi  415250 Feb 27 13:08 libdwtlift.a
-rw-r--r-- 1 pi pi  415250 Feb 27 13:08 libopenjp2.a
when ./compile.sh is executed should be 23
Word count libopenjp2_obj.txt in /home/pi/t_ultibo/src/lib/openjp2
plus dwtlift.o
 23  23 190 libopenjp2_obj.txt

pi@mypi3-1:~/jpeg-2000-test/bare-metal/openjp $ tftp 192.168.1.185 < cmdstftp
tftp> tftp> Sent 2984884 bytes in 12.3 seconds

pi@mypi3-1:~ $ tftp 192.168.1.185
tftp> binary
tftp> get test.j2k
Received 100660 bytes in 0.5 seconds
tftp> quit

pi@mypi3-1:~/t_ultibo/build/bin $ ./opj_decompress -i ~/test.j2k -o decomp.bmp

[INFO] Start to read j2k main header (14740744).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Generated Outfile decomp.bmp
decode time: 3897 ms