When the following is included in a Python program. from __future__ import division from __future__ import print_function Results in an error module de_interleave see below
TypeError: list indices must be integers, not float

Performed a search

http://stackoverflow.com/questions/13355816/typeerror-list-indices-must-be-integers-not-float

It looks like you are using Python 3.x. One of the important differences in Python 3.x is the way division is handled. When you do x / y, an integer is returned in Python 2.x because the decimal is truncated (floor division). However in 3.x, the / operator performs 'true' division, resulting in a float instead of an integer (e.g. 1 / 2 = 0.5). What this means is that your are now trying to use a float to reference a position in a list (e.g. my_list[0.5] or even my_list[1.0]), which will not work as Python is expecting an integer. Therefore you may first want to try using middle = (first + last) // 2, adjusting so that the result returns what you expect. The // indicates floor division in Python 3.x.
Original lines
            if row % 2 == 0:
                temp_bank[col][row/2] =  m[row][col]
            else:
                temp_bank[col][row/2 + height/2] =  m[row][col]

Fix fo Python 3.x
def de_interleave(m,height,width):
    # de-interleave
    temp_bank = [[0]*width for i in range(height)]
    for row in range(width):
        for col in range(width):
            # k1 and k2 scale the vals
            # simultaneously transpose the matrix when deinterleaving
            if row % 2 == 0:
                temp_bank[col][row//2] =  m[row][col]
            else:
                temp_bank[col][row//2 + height//2] =  m[row][col]
    # write temp_bank to s:
    for row in range(width):
        for col in range(height):
            m[row][col] = temp_bank[row][col]
Now (co)simulation works okay.

AMD 6 core

vidal@ws009:~/wkg/jpeg-2000-test/pc_fast_blinker_jpeg$ time python test_dwt_top.py
compiling ...
  *iverilog -o dwt_top ./dwt_top.v ./tb_dwt_top.v
cosimulation setup ...
  *vvp -m ./myhdl.vpi dwt_top
start (co)simulation ...
83121148 :256 256
 3121148: writing test1_256_fwt1pass.png

real	4m24.385s
user	4m31.900s
sys	0m57.627s

RPi2B
pi@mysshserver ~/jpeg-2000-test/pc_fast_blinker_jpeg $ time /opt/pypy-4.0.1-linux-armhf-raspbian/bin/pypy test_dwt_top.py
compiling ...
  *iverilog -o dwt_top ./dwt_top.v ./tb_dwt_top.v
cosimulation setup ...
  *vvp -m ./myhdl.vpi dwt_top
start (co)simulation ...
83121148 :256 256
 3121148: writing test1_256_fwt1pass.png

real	5m29.890s
user	3m52.390s
sys	1m37.280s